name: Build
on:
  push:

jobs:
# Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false
      - run: ./build.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      
        
      
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          sudo apt update
          cargo install cargo-ndk
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android 
          cd ${{ github.workspace }}
          cargo ndk --platform 21 --target aarch64-linux-android build -o bin


      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.so
        #  path: ${{ steps.buildozer.outputs.filename }}
