name: Clear all Github actions caches on sundays
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  my-job:
    name: Delete all caches
    runs-on: ubuntu-latest

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: 'true'